language: php
php:
  - '5.6'
  - '7.0'
install:
  - composer install
  - mysql -e "CREATE DATABASE wscontest_tests;" -uroot
  - cp config.dist.php tests/config.php
  - echo "\$dbUser = 'root';\$dbPass = '';\$dbName = 'wscontest_test';" > tests/config.php
  - bin/wscontest upgrade

script:
  - vendor/bin/parallel-lint . --exclude vendor/
  - vendor/bin/phpcs -p -s
  - vendor/bin/minus-x check .
  - vendor/bin/phpunit
