language: php
services: mysql

php:
  - '7.2'

install:
  - composer install
  - mysql -e "CREATE DATABASE wscontest_tests;" -uroot
  - cp config.dist.php tests/config.php
  - echo -e "\$dbUser = 'root';\n\$dbPass = '';\n\$dbName = 'wscontest_tests';" >> tests/config.php

script:
  - composer test
