language: php
services: mysql
php:
  - '5.6'
  - '7.0'
install:
  - composer install
  - mysql -e "CREATE DATABASE wscontest_tests;" -uroot
  - cp config.dist.php tests/config.php
  - echo -e "\$dbUser = 'root';\n\$dbPass = '';\n\$dbName = 'wscontest_tests';" >> tests/config.php

script:
  - vendor/bin/parallel-lint . --exclude vendor/
  - vendor/bin/phpcs -p -s
  - vendor/bin/minus-x check .
  - vendor/bin/phpunit
